# Generated by Django 5.2 on 2025-04-19 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, choices=[('USA', 'Estados Unidos'), ('BRAZIL', 'Brasil'), ('CANADA', 'Canada'), ('ARGENTINA', 'Argentina'), ('MEXICO', 'Mexico'), ('UK', 'Reino Unido'), ('GERMANY', 'Alemania'), ('FRANCE', 'Francia'), ('SPAIN', 'Espanha'), ('ITALY', 'Italia')], max_length=100, null=True)),
            ],
        ),
    ]
